packages:
  # Backend
  - "backend"

  # Frontend
  - "frontend"

  # Shared packages
  - "packages/*"

  # Tests E2E
  - "e2e"
allowBuilds:
  "@swc/core": false
  bcrypt: false
  esbuild: false
  msw: false
