export declare const STATISTIC_TYPE_MAX_LENGTH = 50;
export declare const STATISTIC_TYPE_MIN_LENGTH = 1;
export declare const STATISTIC_KEY_MAX_LENGTH = 100;
export declare const STATISTIC_KEY_MIN_LENGTH = 1;
export declare const STATISTIC_VALUE_MAX_LENGTH = 65535;
export declare const STATISTIC_VALUE_MIN_LENGTH = 1;
export declare const STATISTIC_TYPES: {
    readonly ATTENDANCE: "frequentation";
    readonly REVENUE: "revenue";
    readonly REGISTRATIONS: "inscriptions";
    readonly PAYMENTS: "paiements";
    readonly COURSES: "cours";
    readonly USERS: "utilisateurs";
    readonly RESERVATIONS: "reservations";
    readonly STORE: "magasin";
};
export declare const INFORMATION_KEY_MAX_LENGTH = 100;
export declare const INFORMATION_KEY_MIN_LENGTH = 1;
export declare const INFORMATION_VALUE_MAX_LENGTH = 65535;
export declare const INFORMATION_VALUE_MIN_LENGTH = 1;
export declare const INFORMATION_DESCRIPTION_MAX_LENGTH = 65535;
export declare const INFORMATION_KEYS: {
    readonly CLUB_NAME: "club_name";
    readonly CLUB_ADDRESS: "club_address";
    readonly CLUB_PHONE: "club_phone";
    readonly CLUB_EMAIL: "club_email";
    readonly CLUB_WEBSITE: "club_website";
    readonly OPENING_HOURS: "opening_hours";
    readonly SOCIAL_FACEBOOK: "social_facebook";
    readonly SOCIAL_INSTAGRAM: "social_instagram";
    readonly SOCIAL_TWITTER: "social_twitter";
    readonly BANK_ACCOUNT: "bank_account";
    readonly VAT_NUMBER: "vat_number";
    readonly LEGAL_INFO: "legal_info";
    readonly THEME_PRIMARY_COLOR: "theme_primary_color";
    readonly THEME_SECONDARY_COLOR: "theme_secondary_color";
    readonly THEME_SIDEBAR_BG: "theme_sidebar_bg";
    readonly THEME_SIDEBAR_TEXT: "theme_sidebar_text";
    readonly CLUB_LOGO_URL: "club_logo_url";
    readonly NAVBAR_NAME: "navbar_name";
    readonly MODULE_DASHBOARD: "module_dashboard";
    readonly MODULE_COURSES: "module_courses";
    readonly MODULE_USERS: "module_users";
    readonly MODULE_FAMILIES: "module_families";
    readonly MODULE_PAYMENTS: "module_payments";
    readonly MODULE_STORE: "module_store";
    readonly MODULE_MESSAGES: "module_messages";
    readonly MODULE_STATISTICS: "module_statistics";
    readonly ACTIVE_MODULES: "active_modules";
    readonly APP_LANGUAGE: "app_language";
    readonly DATE_FORMAT: "date_format";
    readonly TIME_FORMAT: "time_format";
    readonly TIMEZONE: "timezone";
};
export declare const STATISTICS_DEFAULT_PAGE_SIZE = 20;
export declare const STATISTICS_MAX_PAGE_SIZE = 100;
export declare const STATISTICS_MIN_PAGE_SIZE = 1;
export declare const STATISTICS_DEFAULT_PAGE = 1;
export declare const STATISTICS_VALID_SORT_ORDERS: readonly ["asc", "desc"];
export declare const STATISTICS_DEFAULT_SORT_ORDER = "desc";
export declare const MAX_STATISTICS_DATE_RANGE_DAYS = 365;
//# sourceMappingURL=statistics.constants.d.ts.map